// Generated by Wrangler on Thu Apr 11 2024 13:20:42 GMT+0800 (中国标准时间)
// by running `wrangler types`

export {};
declare global {
	const CALLS_APP_ID: "e8c1e71d55a13bb6896980aff884608f";
	const CALLS_APP_SECRET: string;
	const rooms: DurableObjectNamespace;
}
